description: v-jialzhu SHMR

target:
  service: sing
  name: msroctovc
  vc: gcr-singularity-octo


environment:

  image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel:20220629T153823176

  setup:
    # Create conda environment
    - conda create -n SSHMR python=3.8 -y
    - source activate SSHMR
    # Install ffmpeg
    - conda install ffmpeg
    # Install PyTorch
    - conda install pytorch==1.8.0 torchvision cudatoolkit=10.2 -c pytorch -y
    # Install PyTorch3D
    - conda install -c fvcore -c iopath -c conda-forge fvcore iopath -y
    - conda install -c bottler nvidiacub -y
    - conda install pytorch3d -c pytorch3d -y
    # Install mmcv-full
    - pip install "mmcv-full>=1.3.17,<1.6.0" -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
    # Optional: install mmdetection & mmpose & mmtracking
    - pip install "mmdet<=2.25.1"
    - pip install "mmpose<=0.28.1"
    - pip install "mmcls<=0.23.2" "mmtrack<=0.13.0"
    # download azcopy
    - cd ~
    - mkdir download
    - cd download
    - wget https://aka.ms/downloadazcopy-v10-linux
    - tar -xvf downloadazcopy-v10-linux
    # git clone repo
    - cd ~
    - mkdir repo
    - cd reop
    - git clone https://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@github.com/TzRain/SSHMR SSHMR
    - cd SSHMR
    - pip install wandb
    - pip install -r requirements.txt
    - pip install -U numpy
    - pip install -v -e .
    #git azcopy dataset
    # - ~/download/azcopy_linux_amd64_10.16.0/azcopy cp https://bingdatawu2premium.blob.core.windows.net/fwd-data/jialzhu/SSHMR/data?sv=2021-04-10&ss=btqf&srt=sco&st=2022-08-29T06%3A56%3A14Z&se=2022-08-30T06%3A56%3A14Z&sp=rwl&sig=240ZFdHjdBU8istpeIU4%2F%2BMF4mhcJZN0VpXbJ4wH6CY%3D" .   --recursive=true
    


code:
  local_dir: $CONFIG_DIR/


storage:
  data:
    storage_account_name: bingdatawu2premium
    container_name: fwd-data
    mount_dir: /mnt/data

jobs:

  - name: SHMR 0
    sku: 16G4
    process_count_per_node: 0
    command: 
      - cd ~/repo/SSHMR && ./tools/dist_train.sh configs/sshmr/sshmr.py work_dirs/sshmr 4 --no-validate
      - sleep 2h
    execution_mode: basic